version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${DB_POSTGRES}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    environment:
      FLASK_ENV: development
      DB_POSTGRES: ${DB_POSTGRES}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5000:5000"
    depends_on:
      - db
    command: >
        sh -c "sleep 5; python init_db.py && flask run --host=0.0.0.0"
        
volumes:
  pgdata:
